import { Coffee, Lightbulb, Rocket, Star, Trophy } from "lucide-react"

function mods(from: number, to: number) {
  return Array.from({ length: to - from + 1 }, (_, i) => `m${String(i + from).padStart(2, "0")}`)
}

export const PARTS = [
  { number: 1,  title: "Foundations",             modules: mods(1,  7),  color: "#4ECDC4" },
  { number: 2,  title: "Cloud Software Platforms", modules: mods(8,  12), color: "#9B6FD0" },
  { number: 3,  title: "VAT",                      modules: mods(13, 20), color: "#E8B84B" },
  { number: 4,  title: "Payroll PAYE & CIS",        modules: mods(21, 26), color: "#52D98B" },
  { number: 5,  title: "Year-End Accounts",         modules: mods(27, 34), color: "#E87B6F" },
  { number: 6,  title: "Corporation Tax",           modules: mods(35, 40), color: "#6FA8E8" },
  { number: 7,  title: "Self Assessment",           modules: mods(41, 48), color: "#E87BB8" },
  { number: 8,  title: "Incorporation",             modules: mods(49, 57), color: "#4ECDC4" },
  { number: 9,  title: "Cessation",                 modules: mods(58, 66), color: "#52D98B" },
  { number: 10, title: "Structure Changes",         modules: mods(67, 74), color: "#E8B84B" },
  { number: 11, title: "Specialist Tax",            modules: mods(75, 82), color: "#9B6FD0" },
  { number: 12, title: "Practice & Ethics",         modules: mods(83, 87), color: "#4ECDC4" },
]

export const MODULE_TITLES: Record<string, string> = {
  m01: "UK Compliance Landscape",       m02: "UK Business Structures",
  m03: "Double-Entry Bookkeeping",      m04: "Chart of Accounts",
  m05: "Bookkeeping Cycle",             m06: "Source Documents",
  m07: "Cash vs Accruals Basis",        m08: "Dext",
  m09: "Xero",                          m10: "QuickBooks Online",
  m11: "Sage Business Cloud",           m12: "FreeAgent",
  m13: "VAT Fundamentals",              m14: "VAT Schemes",
  m15: "VAT on Goods",                  m16: "VAT on Services",
  m17: "VAT on Land & Property",        m18: "Partial Exemption",
  m19: "VAT Errors & Penalties",        m20: "Making Tax Digital (VAT)",
  m21: "PAYE Fundamentals",             m22: "Statutory Payments",
  m23: "Auto-Enrolment Pensions",       m24: "Benefits in Kind & P11D",
  m25: "Year-End Payroll",              m26: "CIS",
  m27: "Year-End Process",              m28: "Adjusting Journals",
  m29: "FRS 105 Micro-Entity",          m30: "FRS 102 Section 1A",
  m31: "FRS 102 Full",                  m32: "Disclosure Reasoning",
  m33: "iXBRL Tagging",                 m34: "Companies House Filing",
  m35: "Corporation Tax Fundamentals",  m36: "Adjusting to Taxable Profit",
  m37: "Capital Allowances",            m38: "R&D Tax Relief",
  m39: "Loss & Group Relief",           m40: "CT600 Walkthrough",
  m41: "SA100 Main Return",             m42: "SA103 Self-Employment",
  m43: "SA105 Property Income",         m44: "SA108 Capital Gains",
  m45: "SA104 Partnership Income",      m46: "SA109 Residence & Domicile",
  m47: "Tax Calculation & PoA",         m48: "SA Reliefs",
  m49: "Choosing a Structure",          m50: "Sole Trader Setup",
  m51: "Partnership Setup",             m52: "Ltd Company Setup",
  m53: "LLP Setup",                     m54: "Charity Registration",
  m55: "Sole Trader → Ltd",             m56: "Partnership → LLP / Ltd",
  m57: "First-Year Filings",            m58: "Sole Trader Cessation",
  m59: "Partnership Cessation",         m60: "Ltd Strike-Off (DS01)",
  m61: "Members' Voluntary Liquidation",m62: "Creditors' Voluntary Liquidation",
  m63: "Compulsory Liquidation",        m64: "Administration & CVA",
  m65: "Final Accounts on Cessation",   m66: "Capital Distributions & BADR",
  m67: "Ltd → Sole Trader",             m68: "Sole Trader → Partnership",
  m69: "Partnership → Ltd",             m70: "Group Restructuring",
  m71: "Ltd → Charity / CIO",           m72: "Asset Sale vs Share Sale",
  m73: "Demergers",                     m74: "Reconstructions",
  m75: "IR35 / Off-Payroll",            m76: "Inheritance Tax",
  m77: "Stamp Duty Land Tax",           m78: "CGT Reliefs",
  m79: "Trusts",                        m80: "Non-Domiciled Status",
  m81: "HMRC Enquiries",                m82: "Penalty Regimes",
  m83: "AML & MLR 2017",                m84: "Professional Ethics",
  m85: "Engagement Letters",            m86: "GDPR for Accountants",
  m87: "Professional Indemnity Insurance",
}

export const MOTIVATIONAL = [
  { icon: Coffee,    text: "One module a day keeps the confusion away." },
  { icon: Lightbulb, text: "Alex is ready to guide you through any topic." },
  { icon: Rocket,    text: "The UK's best accounting minds started exactly here." },
  { icon: Star,      text: "Consistency beats intensity — keep your streak going." },
  { icon: Trophy,    text: "Every module completed is a skill gained for life." },
]
